// Curated pool for the Idea page's one-button random generation — no
// wizard, no text input, just a decent starting image to hand off into
// Intake. Kept broad/tasteful stock-photo subject matter, no people (avoids
// face-generation quality issues and likeness concerns for a random pick).
export const IDEA_PROMPTS = [
  'a red sailboat on calm ocean water at golden hour',
  'a vintage typewriter on a worn wooden desk',
  'a steaming cup of coffee next to an open notebook',
  'a lighthouse on a rocky coastline at dusk',
  'a stack of old hardcover books with a pair of reading glasses',
  'a bowl of fresh strawberries on a marble countertop',
  'a mountain lake reflecting snow-capped peaks',
  'a bicycle leaning against a brick wall covered in ivy',
  'a rustic farmhouse table set for a dinner party',
  'a hot air balloon drifting over rolling green hills',
  'a cozy fireplace with stacked firewood and a wool blanket',
  'an old wooden pier extending into misty water',
  'a bouquet of wildflowers in a glass mason jar',
  'a city skyline at night with lit windows',
  'a vintage car parked on a quiet cobblestone street',
  'a field of lavender under a soft pastel sky',
  'a stack of pancakes with maple syrup and berries',
  'a potted succulent garden on a sunny windowsill',
  'a wooden rowboat resting on a foggy riverbank',
  'a bakery display case full of fresh pastries',
  'a desert landscape with sand dunes at sunset',
  'a cast iron skillet with a sizzling steak',
  'an open road cutting through autumn forest',
  'a ceramic teapot and cups on a bamboo tray',
  'a waterfall cascading into a clear turquoise pool',
  'a barn surrounded by golden wheat fields',
  'a pair of hiking boots on a mountain trail',
  'a chalkboard menu outside a small cafe',
  'a greenhouse full of blooming orchids',
  'a snow-covered pine forest at dawn',
  'a fruit stand overflowing with citrus at a farmers market',
  'a vintage camera resting on a leather journal',
  'a rooftop garden overlooking a busy city',
  'a wooden dock at sunrise with light fog on the water',
  'a bowl of ramen with steam rising, chopsticks resting on the side',
  'a lighthouse keeper cottage on a cliff edge',
  'a stack of colorful macarons on a marble plate',
  'a hammock strung between two palm trees on a beach',
  'a vineyard at sunset with rows of grapevines',
  'a cup of hot cocoa with marshmallows by a frosted window',
  'a wooden canoe on a still lake surrounded by autumn trees',
  'an old stone bridge over a quiet stream',
  'a bowl of fresh pasta with basil and parmesan',
  'a meadow of sunflowers stretching to the horizon',
  'a candle burning next to a stack of folded linen',
  'a coastal cliffside town with colorful houses',
  'a picnic basket on a checkered blanket in a park',
  'a jar of honey with a wooden dipper on a rustic table',
  'a night sky full of stars over a quiet campsite',
  'a bicycle basket filled with fresh flowers',
]

export function randomIdeaPrompt() {
  return IDEA_PROMPTS[Math.floor(Math.random() * IDEA_PROMPTS.length)]
}
